### ISSUE TITLE
IconTypes aren't actually available

### ISSUE THREAD

**Issue by ndejesus1227** [entria/react-native-fontawesome#43]
I'd like to use IconTypes for the branding styles of my icons. I'm using version 5.7.0, however, when I look at the node_modules/Icons file, I don't see any IconTypes object getting exported. I've uninstalled and reinstalled with no luck. Any idea why this might be happening?

**Comment by jgcmarins** [comment]
which version?

**Comment by leandrosimoes** [comment]
I think that's because npm has not the last commit. A new release must be created. You can see a open issue for this here: [#26](https://github.com/entria/react-native-fontawesome/issues/26)
Until then, you can install the last commit with npm with this command:

`npm install --save git://git@github.com:entria/react-native-fontawesome.git`

Let me know if this was the problem.

**Comment by ndejesus1227** [comment]
Don't need it anymore, but thanks for the responses!
