### ISSUE TITLE
Library searching for fonts with underscores in name, rather than default dashes.

### ISSUE THREAD

**Issue by MattCastellana** [entria/react-native-fontawesome#57]
Over the past while, I've been experiencing an issue that it seems a number of other users are having as well. Essentially, when I install everything and run, the app won't render fontawesome and shows Question marks or X's instead. 

It seems that,  in newer versions of Font Awesome, fonts are named 'fa-regular-400.ttf" (Using dashes), and I think the issues people are having might be stemming from this.

After messing around for a bit, I've found out that the library is searching for font files with underscores (Eg. 'fa_regular_400'), instead of the default filenames with dashes (Eg. 'fa-regular-400'), which causes it to not load the font correctly.  After renaming the files and relinking, everything worked perfectly.

I'm not sure if this is a bug or possibly a configuration issue.  But regardless, I thought I'd post this here to help anyone who may be having similar issues, and let the devs know in case this is a bug.

**Comment by glasje** [comment]
with help I can solve it .. I leave the link
https://github.com/entria/react-native-fontawesome/issues/55

**Comment by leandrosimoes** [comment]
There is a PR for this here: https://github.com/entria/react-native-fontawesome/pull/52

**Comment by jgcmarins** [comment]
@leandrosimoes are we ready to merge?

**Comment by leandrosimoes** [comment]
@jgcmarins Yes, I think so, you already approved my PR, tell me if you need anything else.

**Comment by KalebMatthews** [comment]
Just wanted to mention that the name given from the automatic linking process is different than the file names in the download link for manual linking. The only way I can see to make this package 100% on the setup is to either add the renaming of the files if you link the fonts manually in the readme or change the link to install the fonts to be a package you put up with the naming that matches the automatic names.

Just thought I would give y'all a heads up incase you were unaware of this. It's a TINY thing but since this issue already deals with it I thought I would include it here.

Here are the names given for the automatic linking process:
- FontAwesome5_Regular
- FontAwesome5_Solid
- FontAwesome5_Brands

**Comment by leandrosimoes** [comment]
I open a PR with that solves the hyphens problem, allowing to use the original files with hyphens. https://github.com/entria/react-native-fontawesome/pull/61

In this PR has a working sample project to so you can see how to use properly, because there are some breaking changes on it.

**Comment by leandrosimoes** [comment]
A [new version](https://www.npmjs.com/package/react-native-fontawesome) was released, please, check if in the new version this problem was fixed and feel free to reopen this issue if wasn't. 

**PS: REMEBER TO SEE THE NEW DOCUMENTATION BECAUSE THERE ARE SOME BREAKING CHANGES**
